name: Print Commit Message

on: 
    push:
        branches:
            - master # Trigger on push to any branch
jobs:
    printCommitMessage:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout
              
            - name: Print Commit Message
              run: echo "Commit message  ${{github.event.head_commit.message}}"